### ISSUE TITLE
CSFML sfShader_createFromFile

### ISSUE THREAD

**Issue by DJMaster** [SFML/CSFML#100]
While playing with the Shader.cpp example I've discovered a missing feature within the CSFML binding.

I'm talking about the sfShader_createFromFile function. The creation of a shader passing "vert", "geom" and "frag" files is not implemented. Therefore it is not possible to convert Geometry shader example from Shader.cpp to native C code using CSFML as binding, furthermore it's not possible to create a Shader passing a "geom" shader.

I could modify sfShader_createFromFile function by adding the missing "geom" parameter, but this certanly would break backward compatibility.

Please let me know what you think about this issue.

**Comment by BlaXpirit** [comment]
This is a new feature that hasn't been in any SFML release, and nobody has worked on including it into CSFML yet.

**Comment by BlaXpirit** [comment]
Backwards compatibility is interesting to consider, but I'm not sure if CSFML has such guarantees. Personally I'd prefer keeping it clean (just edit the existing constructor), but I have no say in this.

**Comment by zsbzsb** [comment]
I will be updating CSFML/SFML.Net with the changes once SFML 2.4 is released.

**Comment by DJMaster** [comment]
I've modified CSFML to allow loading of all three vertex + geometry + fragment shaders:

https://github.com/DJMaster/CSFML/tree/shader-patch

I consider this patch a temporary workaround because IMHO shader loading should be implemented better within SFML directly. Let's discuss about this point, please.

![vertex geometry fragment shaders](https://cloud.githubusercontent.com/assets/12114234/17492274/5602fe80-5dab-11e6-87b3-f55683f073ce.png)

**Comment by dabbertorres** [comment]
@LaurentGomila I believe this can be closed, as this was added in the update to 2.4 (used @DJMaster 's branch).
