### ISSUE TITLE
sfGlslBVec* types contain `bool` fields, which is not a valid C primitive

### ISSUE THREAD

**Issue by crumblingstatue** [SFML/CSFML#105]
Example:
```c
typedef struct
{
    bool x;
    bool y;
    bool z;
    bool w;
} sfGlslBvec4;
```

`Glsl.h` fails to compile with a C compiler due to this.

C *does* have `stdbool.h`, which defines a `bool` type, but AFAIK, this is not guaranteed to be the same `bool` type that C++ has. I am unsure what to do here. Is it required that the CSFML structs have the same size and layout as their C++ counterparts?

cc @dabbertorres (#102)

**Comment by dabbertorres** [comment]
This is completely my bad, my apologies. All sfGlslBVec* should have sfBool members, not bool.

I'm surprised it compiled and ran fine for me.

**Comment by crumblingstatue** [comment]
> I'm surprised it compiled and ran fine for me.

CSFML itself is built using a **C++** compiler, so just building CSFML doesn't guarantee it will build with a **C** compiler.

**Comment by dabbertorres** [comment]
Sorry, I meant tests, for which I at least intended to use a C compiler. I
may have accidentally used a C++ compiler.

Regardless, again, sorry about this!
