### ISSUE TITLE
Any suggestions on setting up a Windows compile

### ISSUE THREAD

**Issue by astr0wiz** [SFML/CSFML#108]
The suggestions on the home page notwithstanding, I had a bit of trouble getting beyond the request for the SFML cmake file.  Yes, the FindSFML.cmake is in the Modules directory, but it has to be renamed to SFMLconfig.cmake.  Furthermore, the cmake file would only be accepted when I cut and pasted the set commands from CMakeLists.txt in the SFML root directory for the version numbers.  Now, it finds SFML, but it cannot find the dependencies, which are located in the System32 directory.

So, at this point, I thought it would be good to ask for some help.  Do I copy the dlls out of the System32 directory?  If so, where?  Why aren't they found automatically as they are when using CodeBlocks?  Should I load SDKs for all of the dependencies?  Has anyone else built this project on a Windows box?

**Comment by eXpl0it3r** [comment]
These questions would better fit into the [dedicated forum section](http://en.sfml-dev.org/forums/index.php?board=12.0).

**Comment by astr0wiz** [comment]
Thank you.
