### ISSUE TITLE
Please make a release with SFML 2.4 support

### ISSUE THREAD

**Issue by svenstaro** [SFML/CSFML#110]
Support for SFML 2.4 was apparently merged in recently. There should probably be a release with that.

**Comment by eXpl0it3r** [comment]
Releases will come, but first the code needs more testing to make sure that we didn't miss or break anything. If you can, could you build CSFML and see whether it works for you?

**Comment by LaurentGomila** [comment]
I still receive patches after this big update, so yes we need more time until everything's perfectly stable.

**Comment by crumblingstatue** [comment]
Just a heads-up: I am in the process of [reviewing the rust-sfml API to conform to SFML 2.4](https://github.com/jeremyletang/rust-sfml/issues/140), and this requires evaluating whether CSFML meets all needs to achieve that, and if not, I'll create issues/pull requests.

**Comment by eXpl0it3r** [comment]
CSFML 2.4 [has been tagged](https://github.com/SFML/CSFML/tree/2.4) and pre-built binaries for Windows and OS X [uploaded](http://www.sfml-dev.org/download/csfml/).
