### ISSUE TITLE
CSFML 2.3 Windows x64 download is actually x86

### ISSUE THREAD

**Issue by bookdude13** [SFML/CSFML#121]
In general, I am on Windows 10 and linking to the msvc CSFML library doesn't work.

While trying to link CSFML into my project I got the error "csfml-audio.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'". I downloaded CSFML from the x64 link, opened up a Visual C++ 2015 Native Build Tools command prompt, navigated to CSFML-2.3-windows-64-bit/CSFML/lib/msvc, then ran `dumpbin /headers *.lib | findstr machine`. The output was "14C machine (x86)                                                                                                          32 bit word machine", repeated multiple times. It appears that the 64 bit download link was built with a 32 bit target. I think rebuilding CSFML with an x64 target and updating the link should fix this, but haven't tried myself yet.

**Comment by RUSshy** [comment]
Is CSFML just abandonned ? still not updated, and only admin can push it for security concerns (virus or something else)

**Comment by LaurentGomila** [comment]
You're right, nobody is officially maintaining CSFML. We rely on external contributions, and to be honest I'm not sure about the release process. However, it seems that the master branch is in sync with SFML 2.4, so we'll check if we can make a release.

**Comment by eXpl0it3r** [comment]
The x64 version has been rebuilt and updated (also update the x86 version while I was at it).
