### ISSUE TITLE
The libcsfml-audio.a is corrupted (csfml 2.4 x86 Windows)

### ISSUE THREAD

**Issue by Xenoxis** [SFML/CSFML#129]
Hello, I've tried to use the csfml audio part, but the libcsfml-audio.a seems to be corrupted.
TCC compiler tell me that is an invalid lib :
![image](https://user-images.githubusercontent.com/19935648/47938486-7f08e800-dee4-11e8-858e-787738993e4a.png)

But when i use the preceded version (2.3), i've no error about invalid lib (only with undefined symbols, because those functions seems not exist) :
![image](https://user-images.githubusercontent.com/19935648/47938347-102b8f00-dee4-11e8-80b1-b03e011c2e9e.png)

Can you update the archive to get the uncorrupted file ? 
Thanks

**Comment by Xenoxis** [comment]
TCC (Tiny C Compiler) : https://bellard.org/tcc/

I've asked help on the french discord server about SFML, i've send the .a lib and they confirmed to me that the file is corrupted. That's why i've opened an issue.

**Comment by LaurentGomila** [comment]
It's not something to "fix", import files are specific to compilers. There are tools to generate/convert them, or if there's none for TCC, you can recompile SFML to get compatible libraries.

**Comment by eXpl0it3r** [comment]
I'll close this issue, as we aren't really planning on bringing binary compatibility support for TCC not will we backport such a change for the old DLLs.
