### ISSUE TITLE
Update documentation on how to build CSFML for SFML 2.5+ with CMake

### ISSUE THREAD

**Issue by szopeno** [SFML/CSFML#132]
Short description: The instructions for building the package are incomplete for a someone who just wants to try CSFML and has no experience with a package. There is no FindSFML.cmake script required to build CSFML; there is no instruction that sources of SFML has to be present and export CMAKE_PREFIX_PATH=../SFML has to be set.
Severity: low

System: Linux OpenSuse OpenLeap 42.3 (but I think the issue is system-independent)

I have standard SFML rpm packages, no clone of SFML repository, HOWEVER in SFML repository there is a following comment "Since you found the commit the file was removed, you could have also checked the full commit history and seen that we merged a rather large change last week that makes FindSFML.cmake obsolete and instead introduces CMake config files."

The steps:
(1) get clone https://github.com/SFML/CSFML

(2) vi readme.txt
"The FindSFML.cmake script required by CMake to build CSFML, is located in SFML's cmake/Modules/ directory."

(3) ls cmake/
Config.cmake  Macros.cmake

(4) cmake .

CMake Error at src/SFML/CMakeLists.txt:24 (find_package):
  By not providing "FindSFML.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SFML", but
  CMake did not find one.

  Could not find a package configuration file provided by "SFML" (requested
  version 2) with any of the following names:

    SFMLConfig.cmake
    sfml-config.cmake

  Add the installation prefix of "SFML" to CMAKE_PREFIX_PATH or set
  "SFML_DIR" to a directory containing one of the above files.  If "SFML"
  provides a separate development package or SDK, be sure it has been
  installed.

(5) After git clone SFML and setting CMAKE_PREFIX_PATH, make'ing the SFML, finally I could also make CSFML

**Comment by LaurentGomila** [comment]
As you found out, the way to use SFML in CMake has changed. There's no more FindSFML.cmake (the old, deprecated way to find stuff with CMake), it has been replaced with a configuration file (the modern way).

As the error message says, you have to *set "SFML_DIR" to a directory containing one of the above files* (SFMLConfig.cmake); sources are not required and CMAKE_PREFIX_PATH doesn't need to be touched.

The documentation for CSFML has to be updated, though ;)

**Comment by eXpl0it3r** [comment]
Documentation in the readme file has been updated with #162
