### ISSUE TITLE
Question: Incompatible Naming

### ISSUE THREAD

**Issue by BenjaminHolland** [SFML/CSFML#134]
Several existing nuget packages reference binaries that seem to follow a naming scheme not followed by this repo. Was this an intentional change (perhaps to provide a clean break from previous versions) or an oversight?

**Comment by eXpl0it3r** [comment]
So far we never maintained nor created any nuget packages, as such any nuget package out there is simply community provided.

Maintainable nuget packaging has only been added yesterday (#133) and SFML.Net is still undergoing the same process.

Not sure what kind of incompatible naming you're referring to specifically though.

**Comment by BenjaminHolland** [comment]
Cool. Is there anywhere the naming convention for the dlls is documented so
3rd party libraries can update if they want to?

**Comment by eXpl0it3r** [comment]
I still don't fully get what you mean with naming convention.

Do you mean the csfml-Graphics.dll instead of csfml-graphics.dll?

**Comment by eXpl0it3r** [comment]
Oh didn't notice this either. What was the reason to check it to `csfml-(module).dll` instead of `csfml-(module)-2.dll`?

**Comment by Davipb** [comment]
A .NET Core `[DllImport]` has a very limited search range: `X` will become `X.so` and `libX.so` on Linux, and `X.dll` on Windows.

So if we kept the `-2` on Windows, we'd need to make a separate C# Assembly for Windows that specified `[DllImport("csfml-(module)-2")]`, which kind of defeats the purpose of .NET Core (one C# assembly that runs in any supported platform)

**Comment by LaurentGomila** [comment]
Can we have a mapping file for that, that would specify "csfml-graphics -> csfml-graphics-2.dll"? I remember people doing that to make SFML.net work in certain environments.

**Comment by BenjaminHolland** [comment]
@Davipb yes, thats exactly what I was referring to. Existing nuget packages for windows bind to the sfml-(module)-2 naming, so they would be unable to use this package as a dependency (which i think should be considered the best practice) without modifying their code. That said, in most cases modifying the 3rd party libraries would be pretty easy.

**Comment by Davipb** [comment]
Regarding @LaurentGomila
They were probably using [Mono's DllMap](https://www.mono-project.com/docs/advanced/pinvoke/dllmap/), which unfortunately has no equivalent in .NET Core or .NET Standard.

**Regarding this issue**
If maintaining compatibility with existing packages is an absolute priority, we could always just include two exact copies of the windows DLL in the NuGet package, `csfml-(module).dll` and `csfml-(module)-2.dll`, but I don't think that will be necessary.

A search for "SFML" on NuGet.org results in four types of packages:
1. **Packages that just bring SFML.Net to NuGet** ([example](https://www.nuget.org/packages/WinInsider.SFML.System/))  
These are going to be replaced by the official SFML.Net package, so there's no "compatibility" to be had here
2. **Visual C++ packages that contain the C++ SFML** ([example](https://www.nuget.org/packages/sfml-system/))  
The NuGet package structure for C/C++ packages is completely different, so C/C++ projects will be unable to use our CSFML package as a dependency anyway
3. **Packages that use SFML.Net and don't care about CSFML** ([example](https://www.nuget.org/packages/Otter/))  
These packages would have no compatibility issues. Once the SFML.Net NuGet package is released, they can just switch from pre-compiled binaries to NuGet references, and their C# code won't change at all.
4. **[TGUI.Net](https://www.nuget.org/packages/TGUI.Net.win-x64/)**
This is the only problematic package I've found. TGUI.Net depends on SFML.Net and CTGUI. CTGUI depends on CSFML and TGUI. TGUI depends on SFML. SFML.Net depends on CSFML. CSFML depends on SFML. With this kind of "dependency square", I'm not even sure if they would be able to use the CSFML/SFML.Net NuGet packages

If I missed any other type of package, let me know.
But from what I've found, unless we're going to help TGUI.Net sort their dependency graph, there should be no issue in normalizing the name to `csfml-(module)` for cross-platform consistency.

**Comment by eXpl0it3r** [comment]
I assume nuget packages don't support links, i.e. you don't need to ship to assembly but just point the link to the assembly?

I don't think we have a dependency issue with existing packages, if they want to switch, they will have to fully switch the reference and nuget source, that the DLL is called differently won't really be an issue as far as I know.

I'm sure @texus will be happy to switch, once it's ready, so he has to maintain less. 🙂

**Comment by Davipb** [comment]
NuGet seems to just copy the contents of the linked file instead of the link itself, so there's no way to put links inside of NuGet packages as far as I know.

**Comment by texus** [comment]
I have no problem with the dlls being renamed.
I actually partially missed this discussion and only came here when I found out myself that the naming didn't match (when updating my scripts to be compatible with the PR in SFML.Net). So removing the "-2" from the dlls would make my latest build script work without having to make changes :slightly_smiling_face:.

I don't think my dependency graph is fixable, TGUI has to be compiled with the identical SFML version that is used when compiling CSFML (and even then I didn't manage to get things working in the past when CSFML linked statically to SFML). So I don't see any way to rely on another NuGet package, I will have to keep compiling everything myself and shipping all dependencies with TGUI.Net like before.

**Comment by eXpl0it3r** [comment]
Changed the naming with https://github.com/SFML/CSFML/commit/f84ff413a168ebeef676067f1afb1707ce7caff6#diff-9e80aece757761dc5b68f9626ded6f02b9f605f01c1979480e5369712251a284L197-R200
