### ISSUE TITLE
CSFML NuGet Packages

### ISSUE THREAD

**Issue by DemoXinMC** [SFML/CSFML#149]
As per https://github.com/SFML/SFML.Net/issues/174, CSFML doesn't currently provide "plug-and-play" functionality for .NET Framework (.NET Standard 1.X) style libs. This would need to be resolved in the CSFML NuGet package, as SFML.NET relies upon runtimes supplied by CSFML.

Additionally, we need to look at ways to provide CI and automated building of the CSFML NuGet package to cover more platforms (Mac OS is the glaring omission) as well as avoid having to manually package CSFML updates.

**Comment by Balnian** [comment]
@DemoXinMC  If you don't mind I'll open a separate issue for the NuGet platforms support aprt of your comment for more visibility and easier tracking since @Davipb PR #150  is set to close the issue.

**Comment by DemoXinMC** [comment]
I'm going to close this issue and move discussion to the new issue.  I think it's best that we don't attempt to try to add backwards compatibility to legacy frameworks when the current and future framework has a much cleaner, more defined, STABLE standard.
