### ISSUE TITLE
CSFML_DEPRECATED

### ISSUE THREAD

**Issue by rjopek** [SFML/CSFML#156]
Hi, 

This can be corrected, the compilation will proceed without warning:
https://github.com/SFML/CSFML/blob/master/include/SFML/Window/Event.h#L126

```
c:/SFML/include/SFML/Window/Event.h:132:1: warning: type is deprecated [-Wdeprecated-declarations]
 } sfMouseWheelEvent;
 ^
c:/SFML/include/SFML/Window/Event.h:126:9: note: declared here
 typedef struct CSFML_DEPRECATED
```

**Comment by LaurentGomila** [comment]
What can be corrected? We explicitly marked this structure as deprecated, and this is what the compiler tells you.

**Comment by rjopek** [comment]
I haven't tested this later in the code, this problem can be closed.
It's nice if compilation goes without warning. I'm in the process of making linguistic bindings for Harbour with the library CSFML, 
decided to report it to you.

**Comment by LaurentGomila** [comment]
Does the warning shows even if you don't use the enum at all?

**Comment by rjopek** [comment]
Yes, the warning is displayed even if I am not using an enumeration.

**Comment by rjopek** [comment]
On Linux, compiling and linking libraries is fine.
