### ISSUE TITLE
Graphics/Transform.cpp:167:26: warning: comparison between two arrays

### ISSUE THREAD

**Issue by dcb314** [SFML/CSFML#166]
Recent gcc compiler can be made to say:

CSFML-2.5.1/src/SFML/Graphics/Transform.cpp:167:26: warning: comparison between two arrays [-Warray-compare]

Source code is

   return (left->matrix == right->matrix) ? sfTrue : sfFalse;

**Comment by Bqleine** [comment]
That would only compare the first element of the matrices right ?
