### ISSUE TITLE
Cannot set cursor position on Mac OS

### ISSUE THREAD

**Issue by gonmf** [SFML/CSFML#169]
Hello, I have created the example snippet of code:

https://gist.github.com/gonmf/6b980ecdb7e211ef5bb16e8784bd7719

It should create a black window, centered on the screen, half the size of the screen as well, and once every second it should center the cursor location on itself. You can compile using `gcc test.c -o test -std=c99 -Wall -lcsfml-graphics -lcsfml-window`.

I've tested on Linux with `gcc` 8.3.0, `libcsfml-dev` 2.5-1 and it works as expected.

On macOS Catalina 10.15.7, `clang` 12, `csfml` via `brew` 2.5.1, the cursor centering does nothing altogether.

Could you take a look please?

Thank you

**Comment by eXpl0it3r** [comment]
Make sure you're showing the right permission for the cursor, see also: https://github.com/SFML/SFML/issues/1574

**Comment by gonmf** [comment]
Hello, thank you for the quick reply on this holidays season.

I didn't get any permissions popup, but after much searching around the permissions I found this setting to work for me:

<img width="666" alt="Screenshot 2021-12-31 at 16 07 49" src="https://user-images.githubusercontent.com/5512054/147831850-8b8f304f-3615-473e-86c4-ed659e9a21a2.png">

**Comment by eXpl0it3r** [comment]
Glad you figured it out, we may add some documentation (at least for the C++ library) that highlights this macOS restriction
