### ISSUE TITLE
setSmooth feature for Fonts

### ISSUE THREAD

**Issue by dogunbound** [SFML/CSFML#173]
Main SFML has this feature merged: https://github.com/SFML/SFML/pull/1690 

I was hoping to see if and when this feature will reach CSFML. I am no C wiz, so someone else will probably have to implement this. I'm using rust-sfml which uses C bindings, so when this feature lands here, I can update rust-sfml.

**Comment by Bambo-Borris** [comment]
> Main SFML has this feature merged: [SFML/SFML#1690](https://github.com/SFML/SFML/pull/1690)
> 
> I was hoping to see if and when this feature will reach CSFML. I am no C wiz, so someone else will probably have to implement this. I'm using rust-sfml which uses C bindings, so when this feature lands here, I can update rust-sfml.

This is in the 2.6.x branch on the SFML repository, I did implement the changes locally to add this to CSFML but that was part of investigating the 2.6.0 CSFML release. I imagine when CSFML 2.6.0 releases it will become available to the rust-sfml binding maintainers.

**Comment by eXpl0it3r** [comment]
Implemented with #186
