### ISSUE TITLE
Implement remaining SFML 2.6.0 changes

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/CSFML#187]
Credit to @dogunbound for this list from PR #186. I'm moving this list out to its own issue so we can track these changes while we incrementally merge PRs.

---

Basically, we need to slowly go through EVERY pull request and see if any change needs to be made and make those changes. If there aren't any changes needed for a specific pull request, mark it as complete.
todo list:
- [x] https://github.com/SFML/SFML/pull/1477
- [x] https://github.com/SFML/SFML/pull/1509
- [x] https://github.com/SFML/SFML/pull/1561
- [x] https://github.com/SFML/SFML/pull/1563
- [x] https://github.com/SFML/SFML/pull/1576
- [x] https://github.com/SFML/SFML/pull/1624
- [x] https://github.com/SFML/SFML/pull/1739
- [x] https://github.com/SFML/SFML/pull/1960
- [x] https://github.com/SFML/SFML/pull/1519
- [x] https://github.com/SFML/SFML/pull/1608
- [x] https://github.com/SFML/SFML/pull/1628
- [x] https://github.com/SFML/SFML/pull/1657
- [x] https://github.com/SFML/SFML/pull/1658
- [x] https://github.com/SFML/SFML/pull/1652
- [x] https://github.com/SFML/SFML/pull/1665
- [x] https://github.com/SFML/SFML/pull/1697
- [x] https://github.com/SFML/SFML/pull/1774
- [x] https://github.com/SFML/SFML/pull/1776
- [x] https://github.com/SFML/SFML/pull/1853
- [x] https://github.com/SFML/SFML/pull/2038
- [x] https://github.com/SFML/SFML/pull/2083
- [x] https://github.com/SFML/SFML/pull/2271
- [x] https://github.com/SFML/SFML/pull/1499
- [x] https://github.com/SFML/SFML/pull/1553
- [x] https://github.com/SFML/SFML/pull/2040
- [x] https://github.com/SFML/SFML/pull/2222
- [x] https://github.com/SFML/SFML/pull/2297
- [x] https://github.com/SFML/SFML/pull/2298
- [x] https://github.com/SFML/SFML/pull/2323
- [x] https://github.com/SFML/SFML/pull/623
- [x] https://github.com/SFML/SFML/pull/1475
- [x] https://github.com/SFML/SFML/pull/1622
- [x] https://github.com/SFML/SFML/pull/1623
- [x] https://github.com/SFML/SFML/pull/1716
- [x] https://github.com/SFML/SFML/pull/1751
- [x] https://github.com/SFML/SFML/pull/2058
- [x] https://github.com/SFML/SFML/pull/2114
- [x] https://github.com/SFML/SFML/pull/1535
- [x] https://github.com/SFML/SFML/pull/1723
- [x] https://github.com/SFML/SFML/pull/1732
- [x] https://github.com/SFML/SFML/pull/1627
- [x] https://github.com/SFML/SFML/pull/1718
- [x] https://github.com/SFML/SFML/pull/1114
- [x] https://github.com/SFML/SFML/pull/1787
- [x] https://github.com/SFML/SFML/pull/1788
- [x] https://github.com/SFML/SFML/pull/1848
- [x] https://github.com/SFML/SFML/pull/1849
- [x] https://github.com/SFML/SFML/pull/2219
- [x] https://github.com/SFML/SFML/pull/2220
- [x] https://github.com/SFML/SFML/pull/2221
- [x] https://github.com/SFML/SFML/pull/2241
- [x] https://github.com/SFML/SFML/pull/1785
- [x] https://github.com/SFML/SFML/pull/1791
- [x] https://github.com/SFML/SFML/pull/1846
- [x] https://github.com/SFML/SFML/pull/1906
- [x] https://github.com/SFML/SFML/pull/1908
- [x] https://github.com/SFML/SFML/pull/2048
- [x] https://github.com/SFML/SFML/pull/2066
- [x] https://github.com/SFML/SFML/pull/2073
- [x] https://github.com/SFML/SFML/pull/2094
- [x] https://github.com/SFML/SFML/pull/2100
- [x] https://github.com/SFML/SFML/pull/2106
- [x] https://github.com/SFML/SFML/pull/2142
- [x] https://github.com/SFML/SFML/pull/2217
- [x] https://github.com/SFML/SFML/pull/2218
- [x] https://github.com/SFML/SFML/pull/1841
- [x] https://github.com/SFML/SFML/pull/1940
- [x] https://github.com/SFML/SFML/pull/2173
- [x] https://github.com/SFML/SFML/pull/2477
- [x] https://github.com/SFML/SFML/pull/2046
- [x] https://github.com/SFML/SFML/pull/2263
- [x] https://github.com/SFML/SFML/pull/2294
- [x] https://github.com/SFML/SFML/pull/2512
- [x] https://github.com/SFML/SFML/pull/1749
- [x] https://github.com/SFML/SFML/pull/1750
- [x] https://github.com/SFML/SFML/pull/1761
- [x] https://github.com/SFML/SFML/pull/1843
- [x] https://github.com/SFML/SFML/pull/1868
- [x] https://github.com/SFML/SFML/pull/1418
- [x] https://github.com/SFML/SFML/pull/1520
- [x] https://github.com/SFML/SFML/pull/1522
- [x] https://github.com/SFML/SFML/pull/1612
- [x] https://github.com/SFML/SFML/pull/1720
- [x] https://github.com/SFML/SFML/pull/1784
- [x] https://github.com/SFML/SFML/pull/1795
- [x] https://github.com/SFML/SFML/pull/1712
- [x] https://github.com/SFML/SFML/pull/1419
- [x] https://github.com/SFML/SFML/pull/1779
- [x] https://github.com/SFML/SFML/pull/1648
- [x] https://github.com/SFML/SFML/pull/2165
- [x] https://github.com/SFML/SFML/pull/1575
- [x] https://github.com/SFML/SFML/pull/1818
- [x] https://github.com/SFML/SFML/pull/1819
- [x] https://github.com/SFML/SFML/pull/2393
- [x] https://github.com/SFML/SFML/pull/2397
- [x] https://github.com/SFML/SFML/pull/1845
- [x] https://github.com/SFML/SFML/pull/1765
- [x] https://github.com/SFML/SFML/pull/1771
- [x] https://github.com/SFML/SFML/pull/1484
- [x] https://github.com/SFML/SFML/pull/1539
- [x] https://github.com/SFML/SFML/pull/1577
- [x] https://github.com/SFML/SFML/pull/1603
- [x] https://github.com/SFML/SFML/pull/2157
- [x] https://github.com/SFML/SFML/pull/2160
- [x] https://github.com/SFML/SFML/pull/1557
- [x] https://github.com/SFML/SFML/pull/1235
- [x] https://github.com/SFML/SFML/pull/1400
- [x] https://github.com/SFML/SFML/pull/1596
- [x] https://github.com/SFML/SFML/pull/2009
- [x] https://github.com/SFML/SFML/pull/2096
- [x] https://github.com/SFML/SFML/pull/2148
- [x] https://github.com/SFML/SFML/pull/2243
- [x] https://github.com/SFML/SFML/pull/1693
- [x] https://github.com/SFML/SFML/pull/1694
- [x] https://github.com/SFML/SFML/pull/1688
- [x] https://github.com/SFML/SFML/pull/1840
- [x] https://github.com/SFML/SFML/pull/1850
- [x] https://github.com/SFML/SFML/pull/2191
- [x] https://github.com/SFML/SFML/pull/2242
- [x] https://github.com/SFML/SFML/pull/2029
- [x] https://github.com/SFML/SFML/pull/2146
- [x] https://github.com/SFML/SFML/pull/2246
- [x] https://github.com/SFML/SFML/pull/2259
- [x] https://github.com/SFML/SFML/pull/2400
- [x] https://github.com/SFML/SFML/pull/2268
- [x] https://github.com/SFML/SFML/pull/1794
- [x] https://github.com/SFML/SFML/pull/724
- [x] https://github.com/SFML/SFML/pull/1504
- [x] https://github.com/SFML/SFML/pull/1530
- [x] https://github.com/SFML/SFML/pull/1531
- [x] https://github.com/SFML/SFML/pull/1533
- [x] https://github.com/SFML/SFML/pull/1534
- [x] https://github.com/SFML/SFML/pull/1495
- [x] https://github.com/SFML/SFML/pull/1543
- [x] https://github.com/SFML/SFML/pull/1245
- [x] https://github.com/SFML/SFML/pull/1246
- [x] https://github.com/SFML/SFML/pull/1569
- [x] https://github.com/SFML/SFML/pull/1570
- [x] https://github.com/SFML/SFML/pull/1582
- [x] https://github.com/SFML/SFML/pull/1610
- [x] https://github.com/SFML/SFML/pull/1538
- [x] https://github.com/SFML/SFML/pull/1554
- [x] https://github.com/SFML/SFML/pull/1634
- [x] https://github.com/SFML/SFML/pull/1686
- [x] https://github.com/SFML/SFML/pull/1719
- [x] https://github.com/SFML/SFML/pull/1713
- [x] https://github.com/SFML/SFML/pull/1600
- [x] https://github.com/SFML/SFML/pull/1639
- [x] https://github.com/SFML/SFML/pull/1740
- [x] https://github.com/SFML/SFML/pull/1759
- [x] https://github.com/SFML/SFML/pull/1760
- [x] https://github.com/SFML/SFML/pull/1721
- [x] https://github.com/SFML/SFML/pull/1736
- [x] https://github.com/SFML/SFML/pull/531
- [x] https://github.com/SFML/SFML/pull/1580
- [x] https://github.com/SFML/SFML/pull/1532
- [x] https://github.com/SFML/SFML/pull/1790
- [x] https://github.com/SFML/SFML/pull/1687
- [x] https://github.com/SFML/SFML/pull/1804
- [x] https://github.com/SFML/SFML/pull/1581
- [x] https://github.com/SFML/SFML/pull/1814
- [x] https://github.com/SFML/SFML/pull/1731
- [x] https://github.com/SFML/SFML/pull/1806
- [x] https://github.com/SFML/SFML/pull/1549
- [x] https://github.com/SFML/SFML/pull/1820
- [x] https://github.com/SFML/SFML/pull/1951
- [x] https://github.com/SFML/SFML/pull/1953
- [x] https://github.com/SFML/SFML/pull/1900
- [x] https://github.com/SFML/SFML/pull/1941
- [x] https://github.com/SFML/SFML/pull/1434
- [x] https://github.com/SFML/SFML/pull/1443
- [x] https://github.com/SFML/SFML/pull/1047
- [x] https://github.com/SFML/SFML/pull/1644
- [x] https://github.com/SFML/SFML/pull/988
- [x] https://github.com/SFML/SFML/pull/1597
- [x] https://github.com/SFML/SFML/pull/1669
- [x] https://github.com/SFML/SFML/pull/1690
- [x] https://github.com/SFML/SFML/pull/2064
- [x] https://github.com/SFML/SFML/pull/2072
- [x] https://github.com/SFML/SFML/pull/1710
- [x] https://github.com/SFML/SFML/pull/1756
- [x] https://github.com/SFML/SFML/pull/1768
- [x] https://github.com/SFML/SFML/pull/1769
- [x] https://github.com/SFML/SFML/pull/1786
- [x] https://github.com/SFML/SFML/pull/1789
- [x] https://github.com/SFML/SFML/pull/2107
- [x] https://github.com/SFML/SFML/pull/1712
- [x] https://github.com/SFML/SFML/pull/2322
- [x] https://github.com/SFML/SFML/pull/2464
- [x] https://github.com/SFML/SFML/pull/1817
- [x] https://github.com/SFML/SFML/pull/1558
- [x] https://github.com/SFML/SFML/pull/1560
- [x] https://github.com/SFML/SFML/pull/1609
- [x] https://github.com/SFML/SFML/pull/1568
- [x] https://github.com/SFML/SFML/pull/1625
- [x] https://github.com/SFML/SFML/pull/1630
- [x] https://github.com/SFML/SFML/pull/1725
- [x] https://github.com/SFML/SFML/pull/1745
- [x] https://github.com/SFML/SFML/pull/1746
- [x] https://github.com/SFML/SFML/pull/1092
- [x] https://github.com/SFML/SFML/pull/1757
- [x] https://github.com/SFML/SFML/pull/1826
- [x] https://github.com/SFML/SFML/pull/1827
- [x] https://github.com/SFML/SFML/pull/1836
- [x] https://github.com/SFML/SFML/pull/1993
- [x] https://github.com/SFML/SFML/pull/2129
- [x] https://github.com/SFML/SFML/pull/2132
- [x] https://github.com/SFML/SFML/pull/1471
- [x] https://github.com/SFML/SFML/pull/1487
- [x] https://github.com/SFML/SFML/pull/1516
- [x] https://github.com/SFML/SFML/pull/1546
- [x] https://github.com/SFML/SFML/pull/1517
- [x] https://github.com/SFML/SFML/pull/1666
- [x] https://github.com/SFML/SFML/pull/1707
- [x] https://github.com/SFML/SFML/pull/1232
- [x] https://github.com/SFML/SFML/pull/1796
- [x] https://github.com/SFML/SFML/pull/1851
- [x] https://github.com/SFML/SFML/pull/1626
- [x] https://github.com/SFML/SFML/pull/1629
- [x] https://github.com/SFML/SFML/pull/1636
- [x] https://github.com/SFML/SFML/pull/1637
- [x] https://github.com/SFML/SFML/pull/1744
- [x] https://github.com/SFML/SFML/pull/2175
- [x] https://github.com/SFML/SFML/pull/1382
- [x] https://github.com/SFML/SFML/pull/1641
- [x] https://github.com/SFML/SFML/pull/1565
- [x] https://github.com/SFML/SFML/pull/1578

**Comment by ChrisThrasher** [comment]
The most work lies in the SFML patches that add new features so I'll try to list them out here. This should make it easier to understand what work remains and start delegating that to those who volunteer. This is mostly just an inverse of the above list.
* https://github.com/SFML/SFML/pull/1484
* https://github.com/SFML/SFML/pull/1557
* https://github.com/SFML/SFML/pull/1235
* https://github.com/SFML/SFML/pull/1694
* https://github.com/SFML/SFML/pull/1688
* https://github.com/SFML/SFML/pull/2029
* https://github.com/SFML/SFML/pull/1047
* https://github.com/SFML/SFML/pull/1669
* https://github.com/SFML/SFML/pull/1756
* https://github.com/SFML/SFML/pull/1746
* https://github.com/SFML/SFML/pull/1757
* SFML/SFML#1666
* SFML/SFML#1851

**Comment by shane-tran-whitmire** [comment]
I would Highly recommend you put up a draft Pull request of the one you are working on, so others don't accidentally "take" yours.

**Comment by ChrisThrasher** [comment]
Dibs on https://github.com/SFML/SFML/pull/1047

**Comment by ChrisThrasher** [comment]
See PR https://github.com/SFML/CSFML/pull/191

**Comment by dogunbound** [comment]
Dibs on https://github.com/SFML/SFML/pull/1746 

Ill set up a PR later and update this comment with said PR number

**Comment by ChrisThrasher** [comment]
Dibs on SFML/SFML#1851

**Comment by ChrisThrasher** [comment]
Dibs on SFML/SFML#1688

https://github.com/SFML/CSFML/pull/194

**Comment by ChrisThrasher** [comment]
Dibs on SFML/SFML#1669

https://github.com/SFML/CSFML/pull/195

**Comment by ChrisThrasher** [comment]
Dibs on https://github.com/SFML/SFML/pull/1757

https://github.com/SFML/CSFML/pull/196

**Comment by ChrisThrasher** [comment]
I'm marking https://github.com/SFML/SFML/pull/1666 as complete since using `sf::SoundStream::setProcessingInterval` requires inheriting from `sf::SoundStream` and since that is not something we can express in the C interface, I'm not sure it makes sense to add that to CSFML. I suppose we could make a function called `sfSoundStream_setProcessingInterval` but then we're taking a `protected` function and basically making it `public` which doesn't seem quite right.

I also considered adding it to `sfMusic` but `protected` member functions can never be promoted to `public` member functions so this is not something we can call on an instance of `sf::Music` and thus compilation fails.

**Comment by ChrisThrasher** [comment]
Dibs on https://github.com/SFML/SFML/pull/1235

#197

**Comment by ChrisThrasher** [comment]
Dibs on #SFML/SFML#1557

#198

**Comment by shane-tran-whitmire** [comment]
> 

I think it's ok to make protected member variables public in this case. We need to look for another instance of this to really know what we should do though.

**Comment by dogunbound** [comment]
I think I missed taking https://github.com/SFML/SFML/pull/1788 off the needed changes list. @ChrisThrasher could you update that list and check this one off?

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/CSFML/pull/207 for an implementation of https://github.com/SFML/SFML/pull/1484

Last 2.6.0 feature! 🥳

**Comment by ChrisThrasher** [comment]
All done!!

**Comment by svenstaro** [comment]
How about a new CSFML release with these changes?
