### ISSUE TITLE
Add pkg-config support

### ISSUE THREAD

**Issue by hydrasho** [SFML/CSFML#202]
I'm doing a binding for vala, and it's difficult for meson or vala to find csfml without a .pc file.
it would be nice if csfml also had its own pc file

**Comment by eli-schwartz** [comment]
This was done in #188.

**Comment by eXpl0it3r** [comment]
If you use CSFML 2.5.2, does that fix your issue, @hydrasho?

**Comment by hydrasho** [comment]
@eXpl0it3r  Yes it works perfectly I can now just do --pkg=csfml-all and it works :) thanks!

by the way, is there a reason it's called csfml-all instead of csfml? you can close right after this answer :)

**Comment by eXpl0it3r** [comment]
Not sure why it's called like that, maybe to be explicit that it searches all the libs. Maybe you can check the commits or PR(s).
