### ISSUE TITLE
Apple silicon compatibility

### ISSUE THREAD

**Issue by TiluWeb** [SFML/CSFML#209]
SFML is compatible with Clang - ARM64 (OS X 11.0+).
Is it possible to adapt CSFML to support ARM64 devices (Mac M1, M2)?

**Comment by eXpl0it3r** [comment]
We're in the final stretches of updating CSFML to 2.6 brining it inline with SFML 2.6 that brought support for arm64 on macOS.

Have you tried compiling CSFML master with SFML 2.6?

**Comment by ChrisThrasher** [comment]
CSFML already works on ARM Macs

**Comment by TiluWeb** [comment]
@ChrisThrasher I couldn't do it on my Mac M2. I followed the SFML tutorial https://www.sfml-dev.org/tutorials/2.0/start-osx-fr.php and then applied the same logic with the CSFML installation. Do you know of a tutorial that works well? (PS: I also tried with homebrew, but the result is the same).

**Comment by ChrisThrasher** [comment]
You may have to build it from source but I promise it works. I also use an ARM Mac. If you want help setting up your dev environment you can ask in our Discord.

**Comment by Afkari-1** [comment]
> You may have to build it from source but I promise it works. I also use an ARM Mac. If you want help setting up your dev environment you can ask in our Discord.

I was trying to build sfml for my m2 mac can you please share the link to the discord?

**Comment by eXpl0it3r** [comment]
https://discord.gg/nr4X7Fh
