### ISSUE TITLE
Use inheritance to implement wrapper struct types

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/CSFML#222]
We can save code and remove the ugly `This` parameter if we instead inherit from `sf::` types.

Here's an example: https://github.com/SFML/CSFML/compare/master...simplify_sf_buffer

**Comment by eXpl0it3r** [comment]
Does this really work, i.e. is that type not part of the public C interface?

**Comment by ChrisThrasher** [comment]
The C interface doesn’t know anything about how the type is defined. That’s why we’re allowed to do this.

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/CSFML/compare/master...remove_This

I've started implementing this and am liking how it looks. I still think this is something we should pursue. 

For a select few types like `sfShader` we'll need to add some constructors that delegate to the underlying `sf::Shader` constructors but for most types we can rely on aggregate initialization so no more code is required.
