### ISSUE TITLE
2.6.0 release

### ISSUE THREAD

**Issue by svenstaro** [SFML/CSFML#223]
With #187 done I think it'd be great to get a new official 2.6.0 release for this.

**Comment by eXpl0it3r** [comment]
We're on the way there. Ran into some issues last time I was working on the release, so I just need to find another time slot to do it.

The release notes have already been written though 👀 
![image](https://github.com/SFML/CSFML/assets/920861/cb38ff02-81e8-4010-9f62-5af3a043fc2a)

**Comment by svenstaro** [comment]
This done! Congratulations!
