### ISSUE TITLE
pkg-config bad installation path

### ISSUE THREAD

**Issue by nda-cunh** [SFML/CSFML#248]
csfml should not generate the pkg-config in the /usr folder, but in usr/lib as sfml (and other libraries) do.

**Comment by eXpl0it3r** [comment]
What version of CSFML have you used? We've just recently fixed the pkg-config path in #234

**Comment by nda-cunh** [comment]
> What version of CSFML have you used? We've just recently fixed the pkg-config path in #234

I hadn't seen that it was fixed. 
I took the last release and I also saw it in the last arch Linux package. 

by the way, the SFML C++ releases have a bad prefix pkg-config , they point to the ci-cd home.

**Comment by eXpl0it3r** [comment]
> by the way, the SFML C++ releases have a bad prefix pkg-config , they point to the ci-cd home.

You mean the published Linux binaries? Is there a way to fix it?

Given the difference in distros and package setup, it's anyways questionable to provide Linux binaries.

**Comment by nda-cunh** [comment]
> > What version of CSFML have you used? We've just recently fixed the pkg-config path in #234
> 
> I hadn't seen that it was fixed. I took the last release and I also saw it in the last arch Linux package.
> 
> by the way, the SFML C++ releases have a bad prefix pkg-config , they point to the ci-cd home.

I think a simple  prefix=/usr/include it's the better choice (for binary)
pkg-config searches this folder by default

for the others (if there are any) they'll just have to patch or recompile
