### ISSUE TITLE
`setChannelCount` when using `SoundBufferRecorder`

### ISSUE THREAD

**Issue by mgrojo** [SFML/CSFML#256]
When using `SoundBufferRecorder`, how is one supposed to set the channel count?

My impression is that, either a function `sfSoundBufferRecorder_setChannelCount` function is missing, or there should be a way to get a `SoundRecorder` from a `SoundBufferRecorder` in order to call `sfSoundRecorder_setChannelCount`.

**Comment by ChrisThrasher** [comment]
@mgrojo Can you check out https://github.com/SFML/CSFML/pull/294?

**Comment by mgrojo** [comment]
> @mgrojo Can you check out #294?

It looks fine to me. Note however, that I wanted to confirm that they can be added to my binding, but I couldn't get latest CSFML to build with latest SFML, both in master branch.


<pre>$ make
<font color="#A347BA"><b>Consolidate compiler generated dependencies of target csfml-system</b></font>
[ 10%] Built target csfml-system
<font color="#A347BA"><b>Consolidate compiler generated dependencies of target csfml-window</b></font>
[ 12%] <font color="#26A269">Building CXX object src/CSFML/Window/CMakeFiles/csfml-window.dir/Cursor.cpp.o</font>
<b>/home/mgr/src/github/SFML/CSFML/src/CSFML/Window/Cursor.cpp:</b> In function ‘<b>sfCursor* sfCursor_createFromPixels(const uint8_t*, sfVector2u, sfVector2u)</b>’:
<b>/home/mgr/src/github/SFML/CSFML/src/CSFML/Window/Cursor.cpp:36:31:</b> <font color="#C01C28"><b>error: </b></font>‘<b>createFromPixels</b>’ is not a member of ‘<b>sf::Cursor</b>’
   36 |     auto cursor = sf::Cursor::<font color="#C01C28"><b>createFromPixels</b></font>(pixels, convertVector2(size), convertVector2(hotspot));
      |                               <font color="#C01C28"><b>^~~~~~~~~~~~~~~~</b></font>
<b>/home/mgr/src/github/SFML/CSFML/src/CSFML/Window/Cursor.cpp:</b> In function ‘<b>sfCursor* sfCursor_createFromSystem(sfCursorType)</b>’:
<b>/home/mgr/src/github/SFML/CSFML/src/CSFML/Window/Cursor.cpp:47:31:</b> <font color="#C01C28"><b>error: </b></font>‘<b>createFromSystem</b>’ is not a member of ‘<b>sf::Cursor</b>’
   47 |     auto cursor = sf::Cursor::<font color="#C01C28"><b>createFromSystem</b></font>(static_cast&lt;sf::Cursor::Type&gt;(type));
      |                               <font color="#C01C28"><b>^~~~~~~~~~~~~~~~</b></font>
At global scope:
<b>cc1plus:</b> <font color="#2AA1B3"><b>note: </b></font>unrecognized command-line option ‘<b>-Wno-language-extension-token</b>’ may have been intended to silence earlier diagnostics
make[2]: *** [src/CSFML/Window/CMakeFiles/csfml-window.dir/build.make:90: src/CSFML/Window/CMakeFiles/csfml-window.dir/Cursor.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:265: src/CSFML/Window/CMakeFiles/csfml-window.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
</pre>

* 7402e969c97689cbb72d25a67200479ebbd3cf2f in SFML
* 1a95bf0807512d6ded406f9c959af1014647bf82 in CSFML

Have I done something wrong, or aren't both branches kept in line?

In any case, my binding is not updated for version 3, so I guess I won't be able to test this change on my side, for the moment.

**Comment by eXpl0it3r** [comment]
Can you double check that the SFML headers used are actually pointing to the mentioned SFML commit?

Our CI wouldn't pass, if we couldn't build CSFML with the latest SFML version, so this should work.

**Comment by ChrisThrasher** [comment]
CSFML's CI pipeline continuously builds with the latest commit from SFML so those commit hashes you're using should be compatible. If you want to come over to the SFML Discord I'm happy to debug your build issues.

> In any case, my binding is not updated for version 3, so I guess I won't be able to test this change on my side, for the moment.

Seems reasonable to backport this fix to v2. https://github.com/SFML/CSFML/pull/300

**Comment by ChrisThrasher** [comment]
These functions were just merged into 2.6.x so you should be good to update your bindings now!

**Comment by mgrojo** [comment]
With the 2.6.x branches, I was able to update my binding and test the two new functions. Thanks a lot!
