### ISSUE TITLE
How to build static libs using CMake

### ISSUE THREAD

**Issue by jarroddavis68** [SFML/CSFML#309]
Still, I cannot get this to work. I can build SFML static lib via Cmake (gui) no probelm, but when I try to then build CSFML, I get this:
<img width="589" alt="image" src="https://github.com/user-attachments/assets/7e8cf27e-2b8e-4a3e-b59c-0058159acdc3">

**Comment by eXpl0it3r** [comment]
Are you using CSFML master?

Maybe it's because of #286 
Try using `SFML_ROOT` instead

**Comment by jarroddavis68** [comment]
> Are you using CSFML master?
> 
> Maybe it's because of #286 Try using `SFML_ROOT` instead

yes, master. Hmm, don't see a SFML_ROOT branch. Looking at #286 comments, says it was removed.

**Comment by eXpl0it3r** [comment]
Sorry, it's not a branch, I meant use `SFML_ROOT` instead of `SFML_DIR` 😅

**Comment by jarroddavis68** [comment]
Ok, thanks for you help, finally got it to work. Here are a few issues still when trying to build CSFML as a static:
- the target ext remains as .dll rather than .lib (I have to manually change)
- I see the following `could not find` messages, but everything seem to build
![image](https://github.com/user-attachments/assets/be7b9268-e34f-4bfb-a12a-76150e3fe82c)
- `CSMFL_XXX_EXPORTS` are defined so you get inconsistent linkage error (I have to manually define each)
- Finally, if you define a install location for CSFML and run install, as a shared lib build, it will move the files into the correct location, however for static you get this error:
![image](https://github.com/user-attachments/assets/1ec4aa41-a735-44d5-b11c-83b4fae97a90)

**Comment by ChrisThrasher** [comment]
See https://github.com/SFML/CSFML/pull/311

> the target ext remains as .dll rather than .lib (I have to manually change)

I took a look at this and am not sure what is causing it. As far as I'm aware we don't go out of our way to change the file extension of Windows static libs but perhaps I'm overlooking something.

> I see the following could not find messages, but everything seem to build

This is expected and does not signify an error.

> CSMFL_XXX_EXPORTS are not defined so you get inconsistent linkage error (I have to manually define each)

Fixed in #311 

> Finally, if you define a install location for CSFML and run install, as a shared lib build, it will move the files into the correct location, however for static you get this error:

The CI jobs I added in #311 seem to be able to install the static libraries without issue so I'm not sure why it's failing for you.

**Comment by jarroddavis68** [comment]
@ChrisThrasher Thanks!

One thing I forgot, SFML will do /MT, of which I have it set, but CSFML defaults to /MD can you check on this as well?

**Comment by ChrisThrasher** [comment]
I'm not very familiar with those MSVC flags but perhaps CSFML needs to port this change from SFML: https://github.com/SFML/SFML/commit/4970af89992951eb2b4973bf32447445e9b38f64

**Comment by jarroddavis68** [comment]
> I'm not very familiar with those MSVC flags but perhaps CSFML needs to port this change from SFML: [SFML/SFML#1834](https://github.com/SFML/SFML/pull/1834)

/MD (multi-thread DLL) Dynamically links the CRT
/MT (Multi-threaded) Statically links the CRT

Yup, CSFML needs that for sure, should fix the issue. Works as expected when I build SFML. I tick the option to use /MT and all of them will be /MT.

**Comment by ChrisThrasher** [comment]
If I port SFML#1834 to CSFML would you be able to test it out for me?

**Comment by jarroddavis68** [comment]
> If I port [SFML/SFML#1834](https://github.com/SFML/SFML/pull/1834) to CSFML would you be able to test it out for me?

absolutely 👍🏿

**Comment by jarroddavis68** [comment]
@ChrisThrasher happy to report everything works, except /MD. CSFML still defaults all libs to /MD. Everything else, however, seems to work, even the installation, all moved over succesfully.

**Comment by jarroddavis68** [comment]
and do have manually add SFML_ROOT

**Comment by jarroddavis68** [comment]
Ok, correction, I just have to populate CMAKE_INSTALL_PREFIX with the install location of SFML and it will just work, so everything works except linking against static CRT (/MT). I still have to set those manually.

**Comment by ChrisThrasher** [comment]
@jarroddavis68 Try this out https://github.com/SFML/CSFML/tree/msvc_runtime_libs

> and do have to manually add SFML_ROOT

This is to be expected. You have to tell CMake where to find SFML. If you don't install SFML to one of the default locations CMake checks then you'll have to set `SFML_ROOT`.

> Ok, correction, I just have to populate CMAKE_INSTALL_PREFIX with the install location of SFML and it will just wor

This might work but it's very unconventional and I wouldn't recommend it. Using `SFML_ROOT` is the canonical solution.

**Comment by jarroddavis68** [comment]
> @jarroddavis68 Try this out https://github.com/SFML/CSFML/tree/msvc_runtime_libs
> 
![image](https://github.com/user-attachments/assets/4606580f-7ca4-4971-970d-92514f0d6b7c)
Once the install location is set, everything "just works", yah!

But, sadly, still seem to default to /MD
![image](https://github.com/user-attachments/assets/cfdbb680-f552-44a2-8e9c-4e37dc68a11b)

**Comment by ChrisThrasher** [comment]
Did you do a clean build? That will ensure all CMake cache variables get reset.

**Comment by jarroddavis68** [comment]
> EDIT: I fixed a minor issue in my branch related to the `STATIC_STD_LIBS` option. Make sure you enable that if you want static runtime libs.

YES! Works. ❤️ Many thanks!!

**Comment by jarroddavis68** [comment]
Ahh for the first time I'm now able to automatic grabbing the latest sources, compiling to static libs, convert C headers to Delphi and build my Deps DLL that is used by Delphi for my CSFML based projects.

To @ChrisThrasher and @eXpl0it3r, many thanks for all your help! ✊🏿 

https://www.youtube.com/watch?v=grc5nj7AILk

**Comment by jarroddavis68** [comment]
Ok thanks.👌
