### ISSUE TITLE
Intermittent no audio playback device notice

### ISSUE THREAD

**Issue by jarroddavis68** [SFML/CSFML#353]
```
No audio playback devices available on the system
Using NULL audio backend for playback
```
When playback streaming audio, at times, I get the above notice. I can run it again and it works. Any idea what may cause this and how to fix it.

Also, how to have it not display random error messages on the console. Any way that I can just check for errors instead?

**Comment by eXpl0it3r** [comment]
Do you have some sample code?

**Comment by jarroddavis68** [comment]
Hmm, I think its related to audio streaming as I get consistent crashes. I have more tests to do before I have enough info to present. So, for now I will close this until I can determine if it's an actual bug or just because of my implementation.

**Comment by eXpl0it3r** [comment]
Note that between SFML 2 and 3 we replaced OpenAL with miniaudio, so the underlying requirements for audio data streaming might be slightly different in how much and how frequent data is required.

**Comment by jarroddavis68** [comment]
Yea, I noticed miniaudio now and really appreciate it. Makes it much easier to compile as static lib.

It turns out it was an issue on my end. Got that sorted out now.
