### ISSUE TITLE
Add example / test

### ISSUE THREAD

**Issue by gyscos** [SFML/CSFML#52]
It would be a good thing to have a small example program, that could also be used to check that the library works (this would be useful to detect incompatibilities with newer versions SFML that don't appear when compiling the library itself). Unit tests could probably do that too, I don't know which takes more effort to make.

**Comment by BlaXpirit** [comment]
There is something here... https://github.com/LaurentGomila/CSFML/blob/8c9f98f17e1953ed3e262e6edb8fd9c913e0e1c5/doc/mainpage.hpp#L15

**Comment by zsbzsb** [comment]
Not really needed.... there isn't really anything to break that won't break during compilation of CSFML since it is just a thin wrapper. All functionality is included within SFML.

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/CSFML/pull/215
https://github.com/SFML/CSFML/pull/243
https://github.com/SFML/CSFML/pull/245
