### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by eXpl0it3r** [SFML/CSFML#54]
I might do a PR later, but just so it doesn't get forgotten.

When generating the documentation there are quite a few errors generated, see [this Gist](https://gist.github.com/7e773d9ad1f4a7206d2e).

Also after SFML 2.2, we've [updated the doxygen file quite a bit](https://github.com/LaurentGomila/SFML/pull/750), maybe we should apply most of the changes from over there to CSFML as well.

**Comment by zsbzsb** [comment]
Superseded by #92
