### ISSUE TITLE
Track releasing 2.3

### ISSUE THREAD

**Issue by zsbzsb** [SFML/CSFML#70]
This will be where we can track the progress of things that are needed before 2.3 can be released. (I really didn't want a separate issue with milestones for each item)

- [Color int constructor](https://github.com/LaurentGomila/SFML/pull/722) - Done [#71]
- [New mouse scrolling events](https://github.com/LaurentGomila/SFML/pull/810) - Done [#79]
- [Partial send support for TCP](https://github.com/LaurentGomila/SFML/pull/796) - Done [#72]
- [Core context creation and other minor GL functions](https://github.com/LaurentGomila/SFML/issues/654) - Done [#74]
- [Replaced unsigned int with std::size_t for array indices/sizes](https://github.com/SFML/SFML/pull/739) - Done [#77]

**Comment by zsbzsb** [comment]
So unless anybody has anything to add, this will probably be merged in a few days.

**Comment by eXpl0it3r** [comment]
I'll add :+1: :wink:

**Comment by BlaXpirit** [comment]
SFML 2.3 has been released.

I've tried out the updated CSFML on my bindings. `size_t` changes went well. New mouse scroll works.

[API changes between SFML 2.2 and 2.3](https://gist.github.com/BlaXpirit/6d2192f7c444dd57f59c)

**Comment by crumblingstatue** [comment]
Is there anything left to do before CSFML 2.3 can be released?

**Comment by zsbzsb** [comment]
Since 2.3 has been tagged this can be closed.
