### ISSUE TITLE
Fails to build against SFML 2.3 on Mac OS X

### ISSUE THREAD

**Issue by dunn** [SFML/CSFML#81]
I was looking to update the Homebrew formula for SFML (Homebrew/homebrew#39900) but CSFML is having trouble with the new version. It's failing for me with Clang and GCC:

- Clang: https://gist.github.com/dunn/14a075d595a41c22be9e#file-02-make-L165
- GCC: https://gist.github.com/dunn/480f30f21b1ddf081528#file-02-make-L148

And the Homebrew CI bot shows failures for older OSs too: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/26400/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_csfml/

**Comment by eXpl0it3r** [comment]
SFML is not CSFML, as such they are not bound to be always in sync. CSFML master is currently not on version 2.3, there's an open PR though: https://github.com/SFML/CSFML/pull/75
Might want to test against that one or wait till everything is merged.

**Comment by dunn** [comment]
Yeah, the master branch builds fine. Thanks!

**Comment by zsbzsb** [comment]
>Yeah, the master branch builds fine. Thanks!

What were you building before? And I will be tagging the current master as CSFML in just a day or so when I get some more time.

**Comment by dunn** [comment]
I was trying to build http://www.sfml-dev.org/download/csfml/CSFML-2.2-sources.zip

**Comment by dunn** [comment]
Forgot to close this after 2.3 was released, thanks again!
