### ISSUE TITLE
Missing methods on SoundBufferRecorder.

### ISSUE THREAD

**Issue by SpaceManiac** [SFML/CSFML#83]
These functions on `SoundRecorder` are not available on `SoundBufferRecorder`:
```c
void sfSoundRecorder_setProcessingInterval(sfSoundRecorder* soundRecorder, sfTime interval);
sfBool sfSoundRecorder_setDevice(sfSoundRecorder* soundRecorder, const char* name);
const char* sfSoundRecorder_getDevice(sfSoundRecorder* soundRecorder);
```
It seems like at least `setDevice` and `getDevice` variants should be available.

**Comment by LaurentGomila** [comment]
That's right. When something is added to a base class, it must also be duplicated in all the derived classes in CSFML.

**Comment by zsbzsb** [comment]
Superseded by #90
