### ISSUE TITLE
Floating point exception (AV) when using a shader (x64)

### ISSUE THREAD

**Issue by CWBudde** [SFML/CSFML#86]
It might not necessarily a bug in CSFML, but when using a shader in combination with any shape, I get a floating point exception (access violation) on my Win64 system. The same code works fine on when compiled for 32-bit.

Note: I'm not using the original CSFML binding but my PasSfml binding for Pascal, but since the very same code used to work with version 2.2 and there haven't been many changes on the CSFML interface I doubt that it's the different binding.

In my test code the error is exposed when calling sfRenderTexture_drawSprite. If the shader is not specified in the render state it works (not giving the wanted results though).

Since SFML is a spare time project of mine, I don't have much time to invest in this issue, but if someone experiences the same problem (or can tell that it does work), it could already be of help.

**Comment by eXpl0it3r** [comment]
> when using a shader in combination with any shape

Can you be a bit more specific on that? In combination how? etc.

**Comment by zsbzsb** [comment]
Can you post an example (just using CSFML calls) that shows the issue? Otherwise I'm inclined to think that it may be a bug with how your bindings work.

**Comment by CWBudde** [comment]
So far it seems to happen with every shader. This said, I have tried to nail it down to a very simple example.

I guess it needs to be adapted for compiling with plain C, but it's fairly simple to read I hope (given that Pascal was designed as a teaching language):

```pascal
program Circles;

uses
  SysUtils,
  SfmlGraphics,
  SfmlSystem,
  SfmlWindow;

var
  VertexShader, FragmentShader: PAnsiChar;
  RenderTargetHandle: PsfRenderTexture;
  TextureHandle: PsfTexture;
  WindowHandle: PsfRenderWindow;
  Event: TsfEvent;
  States: TsfRenderStates;
  CircleShaderHandle: PsfShader;
  SpriteHandle: PsfSprite;
begin
  States.BlendMode := sfBlendAlpha;
  States.Transform := sfTransformIdentity;

  VertexShader :=
    '#version 110'#10 +
    'precision lowp float;'#10 +
    ''#10 +
    'varying vec2 uv;'#10 +
    ''#10 +
    'void'#10 +
    'main() {'#10 +
    '  gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;'#10 +
    '  uv = vec2(gl_MultiTexCoord0);'#10 +
    '}';
  FragmentShader :=
    '#version 110'#10 +
    'precision lowp float;'#10 +
    ''#10 +
    'varying vec2 uv;'#10 +
    'uniform float Radius;'#10 +
    'uniform vec2 Position;'#10 +
    'uniform vec4 CircleColor;'#10 +
    ''#10 +
    'void'#10 +
    'main() {'#10 +
    '  vec4 color0 = CircleColor;'#10 +
    ''#10 +
    '  vec2 m = uv - Position;'#10 +
    '  float dist = Radius - sqrt(m.x * m.x + m.y * m.y);'#10 +
    ''#10 +
    '  float t = 0.0;'#10 +
    '  if (dist > 2.0)'#10 +
    '    t = 1.0;'#10 +
    '  else if (dist > 0.0)'#10 +
    '    t = 0.5 * dist;'#10 +
    ''#10 +
    '  color0.a = t * color0.a;'#10 +
    '  gl_FragColor = color0;'#10 +
    '}';
  CircleShaderHandle := sfShader_createFromMemory(VertexShader, FragmentShader);
  States.Shader := CircleShaderHandle;

  RenderTargetHandle := sfRenderTexture_create(800, 600, False);
  TextureHandle := sfRenderTexture_getTexture(RenderTargetHandle);

  // Create the main Window
  WindowHandle := sfRenderWindow_create(sfVideoMode(800, 600),
    PAnsiChar('SFML Shader'), [sfTitleBar, sfClose], nil);

  // Start the loop
  while sfRenderWindow_isOpen(WindowHandle) do
  begin
    // Process events
    while sfRenderWindow_pollEvent(WindowHandle, Event) do
    begin
      if Event.EventType = sfEvtClosed then
        sfRenderWindow_close(WindowHandle);
    end;

    SpriteHandle := sfSprite_create;
    try
      sfSprite_setTexture(SpriteHandle, TextureHandle, False);
      sfRenderWindow_drawSprite(WindowHandle, SpriteHandle, nil);
    finally
      sfSprite_destroy(SpriteHandle);
    end;

    sfShader_setColorParameter(CircleShaderHandle, 'CircleColor',
      sfColor_fromRGBA(Random($FF), Random($FF), Random($FF), Random($FF)));
    sfShader_setFloatParameter(CircleShaderHandle, 'Radius', 200 * Random);
    sfShader_setFloat2Parameter(CircleShaderHandle, 'Position', 800 * Random, 600 * Random);

    SpriteHandle := sfSprite_create;
    try
      sfSprite_setTexture(SpriteHandle, TextureHandle, False);
      sfRenderTexture_drawSprite(RenderTargetHandle, SpriteHandle, @States);
    finally
      sfSprite_destroy(SpriteHandle);
    end;

    // Finally, display the rendered frame on screen
    sfRenderWindow_display(WindowHandle);
  end;
end.
```

**Comment by CWBudde** [comment]
I forgot to mention that the AV happens in sfRenderTexture_drawSprite (the second call in the above code).

**Comment by zsbzsb** [comment]
Just to confirm, this happens when only compiling with x64 and what compiler?

**Comment by CWBudde** [comment]
This basically only happens with the recent (v2.3) Win64 DLLs. It does not happen with the 2.2 DLLs (x64) nor with the x86 DLLs in version 2.3.

I have not tried other platforms, simply because I don't have much spare time. It's actually not "my" issue, but an issue of a user of my Pascal bindings. From the first glance the bindings look OK and because it is only not working with the v2.3 x64 DLLs I thought it could be a CSFML problem.

The compilers I have tried so far are FPC (Free Pascal Compiler, version 2.6.4) and some Delphi compilers (XE2 to XE7). Despite the different compilers the error is more or less identical.

**Comment by zsbzsb** [comment]
@CWBudde Looking at the code you posted... any chance you could provide a stacktrace when it crashes?

**Comment by zsbzsb** [comment]
@CWBudde Can you confirm this is still an issue? I really think this was due to something being mismatched or if it is a bug, it would be in SFML as nothing changed in CSFML between the releases.

**Comment by DJMaster** [comment]
Hello Christian,
try to change your code (in 2 places) adding the following ifdef GL_ES:

    '#ifdef GL_ES'#10 +
    'precision lowp float;'#10 +
    '#endif'#10 +

working both i386-win32 and x86_64-win64 targets:

![circles](https://cloud.githubusercontent.com/assets/12114234/16547798/370051d4-4179-11e6-87a8-7f4e51d46c29.png)

**Comment by eXpl0it3r** [comment]
Since we haven't received more information on the issue, I'll close this for now. If it turns out to still be an issue, feel free to reopen.

**Comment by CWBudde** [comment]
I updated the bindings to version 2.4 and (at least) now it seems to work as it should. In addition, the code I supplied wasn't that good, but at least everything is solved now.

**Comment by eXpl0it3r** [comment]
Good to hear! 😊
