### ISSUE TITLE
Ftp::sendCommand is missing

### ISSUE THREAD

**Issue by BlaXpirit** [SFML/CSFML#87]
[Ftp::sendCommand](http://www.sfml-dev.org/documentation/2.2/classsf_1_1Ftp.php#a44e095103ecbce175a33eaf0820440ff) was added in SFML 2.2, is missing from CSFML.

**Comment by zsbzsb** [comment]
Thanks for reporting it, I will fix it soon. :)

**Comment by zsbzsb** [comment]
Let's continue the discussion in #88.
