### ISSUE TITLE
Provide FindSFML.cmake

### ISSUE THREAD

**Issue by crumblingstatue** [SFML/CSFML#89]
What is the rationale behind not providing FindSFML.cmake?

I talked to someone on #cmake, and he stated that projects should provide the FindXXX.cmake for their CMake-based dependencies. (Unless CMake itself officially provides a FindXXX.cmake for a dependency).

This is especially painful if SFML is installed to a non-standard location, as you have to fiddle around with setting CMAKE_MODULE_PATH to the correct location (and that doesn't work if the project overrides CMAKE_MODULE_PATH, which CSFML 2.1 did, although newer versions don't seem to do that anymore).

**Comment by LaurentGomila** [comment]
SFML will soon switch to configuration files, so this won't be an issue anymore.

https://github.com/SFML/SFML/issues/937
https://github.com/SFML/SFML/issues/758

**Comment by zsbzsb** [comment]
I can add one, but I don't care either way. So what is the decision on this?

**Comment by crumblingstatue** [comment]
> I can add one, but I don't care either way. So what is the decision on this?

If configuration files solve this issue, then there is no need.

**Comment by zsbzsb** [comment]
Well then lets close this for now.
