### ISSUE TITLE
Error building csfml with msvc 2010

### ISSUE THREAD

**Issue by aullidolunar** [SFML/CSFML#97]
HI I just build and install a git-ed version of sfml with msvc2010 and it was a success. Now, when trying to build csfml, too from github, I got this error

> CMake Error at X:/usr/cmake/Modules/FindSFML.cmake:358 (message):
>   Could NOT find SFML (missing: SFML_SYSTEM_LIBRARY SFML_WINDOW_LIBRARY
>   SFML_NETWORK_LIBRARY SFML_GRAPHICS_LIBRARY SFML_AUDIO_LIBRARY)
> Call Stack (most recent call first):
>   src/SFML/CMakeLists.txt:26 (find_package)

as you can see cmake it does find the FindSFML.cmake script, but seems that the script doesn't find the development sfml files... any ideas?

**Comment by LaurentGomila** [comment]
SFML must be in the PATH, or you must define the SFML_ROOT CMake variable to let CMake know where SFML is.

Next time please use the forum for help requests, we try to keep the tracker for confirmed bugs and features.
